name: Build and Deploy

on:
  push:
    branches:
      - ukondoz/test-maven-packaging
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        run: mvn --batch-mode --update-snapshots package -Dpackaging=maven-plugin
      - name: Publish
        run: mvn --batch-mode deploy -Dpackaging=maven-plugin
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
