name: Test

on:
  push:
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: [valstro-runner, linux-small]
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: mvn --batch-mode --update-snapshots test